# Generated by Django 5.1.5 on 2025-02-08 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_saved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('savings_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.savingsgoal')),
            ],
        ),
    ]
