# Generated by Django 5.1.5 on 2025-02-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dailysavings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialbook',
            name='published_date',
        ),
    ]
