# Generated by Django 5.1.5 on 2025-02-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_financialbook_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialbook',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
