# Generated by Django 5.1.5 on 2025-02-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_financialbook_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
